using System.IO;
using Firebase;
using Firebase.Database;
using Firebase.Database.Query;
using Newtonsoft.Json.Linq;
using Firebase.Database.Streaming;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.Logging;
using System.Collections;
using Microsoft.VisualBasic.ApplicationServices;
using System.Linq.Expressions;
namespace MainServer
{
    
    public partial class Form1 : Form
    {
        Firebase.Database.FirebaseClient FireClient;
        public Form1()
        {
            InitializeComponent();
            FireClient = new Firebase.Database.FirebaseClient("https://careconnect-1c393-default-rtdb.firebaseio.com/");
        }
     
        private  void Form1_Load(object sender, EventArgs e)
        {
            // -----  the following query gets the added collection in Emegency collection in firebase -------
            var obserable = FireClient.Child("CareConnect/Emergency").AsObservable<object>();
            var Subscription = obserable.Subscribe(async snapshot =>
            {
                if (snapshot.EventType == FirebaseEventType.InsertOrUpdate)
                {
                    string CollectionName = snapshot.Key;  // a random id for each record in emergency collection will be generated by flutter app
                    Emergency emegency = new Emergency();

                    emegency.Ambulance = await FireClient.Child($"CareConnect/Emergency/{CollectionName}/AmbulanceId").OnceSingleAsync<string>();
                    emegency.Location = await FireClient.Child($"CareConnect/Emergency/{CollectionName}/Location").OnceSingleAsync<string>();
                    emegency.FingerPrint = await FireClient.Child($"CareConnect/Emergency/{CollectionName}/FingerPrint").OnceSingleAsync<string>();

                    MessageBox.Show(emegency.ToString());
                }
            }); 

        }
    }
}
